### ISSUE TITLE
Bewertungen repräsentativ machen

### ISSUE THREAD

**Issue by phildhk** [FLXez/dbprog#28]
Also, mein Problem ist, dass ich in der overview nicht weiß was wirklich gut ist. Da steht 5 Sterne.. aber nur Felix der noch nie alkohol zu sich genommen hat hat es bewertet. Finde den Fehler? Okay sagen wir es anders, felix der nicht genug alkohol zu sich nimmt, um etablissements schön zu finden, bewertet das, und ich lese den scheiß nicht, seh nur das average und glaube es. ja FUCK.

**Comment by FLXez** [comment]
Isset.
