### ISSUE TITLE
Feinschliff Datenbankabfragen

### ISSUE THREAD

**Issue by FLXez** [FLXez/dbprog#31]
Jaja ist nicht alles hübsch, macht notfalls selbst

**Comment by FLXez** [comment]
Unter anderem:
Forms action="phpscript.php"
und nicht mehr ?xyz

**Comment by phildhk** [comment]
Sind alle ausgelagert, so done i guess

**Comment by FLXez** [comment]
still dont get why u closed.

**Comment by FLXez** [comment]
Kleiner Tracker für mich:
Done:
- search
- signin
- profil_other
- profil_main
- index
- footer_terms
- footer_privacy
- etablissement_main
- cocktail_main
- cocktail_details (rest Optional)
- about_team
- about_motivation
- about_impressum

Todo:
- etablissement_new
- etablissement_details
- cocktail_new
