### ISSUE TITLE
Mods/Admins

### ISSUE THREAD

**Issue by FLXez** [FLXez/dbprog#42]
Realisiert:
Mods:
- Können Etablissements verifizieren
- Können Etablissements anpassen
- Können Bewertungen melden
- Können Cocktails melden
- Können Etablissements melden
- Können Cocktails anpassen

Admins:
- Können Etablissements verifizieren
- Können Etablissements anpassen
- Können Bewertungen löschen
- Können Cocktails anpassen

TODO:
Admins:
- Können Cocktails löschen
- Können Etablissements löschen
- Können User löschen

**Comment by FLXez** [comment]
@Schnietzel:
Datenbankseitig müssen wir bzgl. DELETE statement noch was klären, damit da kein FK error kommt, weil noch Cocktails zugewiesen sind. Cascade maybe?

**Comment by Schnietzel** [comment]
> @Schnietzel:
> Datenbankseitig müssen wir bzgl. DELETE statement noch was klären, damit da kein FK error kommt, weil noch Cocktails zugewiesen sind. Cascade maybe?

Guter Punkt. Da kommt auch wieder zu tragen, dass wir die Datenbank noch anpassen sollten. Wenn ein Eta gelöscht wird, müssen alle Einträge aus der Speisekarte gelöscht werden, dazu auch die Bewertungen und natürlich die Bewertungen zum Cocktail in dem Etablissement. Kaskadierend klingt mir da richtig
