### ISSUE TITLE
Moderator-Log

### ISSUE THREAD

**Issue by FLXez** [FLXez/dbprog#47]
Neue Tabelle: log
- id
- mod_id
- aktion ENUM(etab_verify, etab_unverify, etab_edit, cock_edit, cock_new, etab_new, cock_etab_new)
- etab_id
- cock_id
- ts

Tabelle existiert.
Workt alles

Logeintrag beim löschen NICHT, da durch CASCADE der Logeintrag wieder gelöscht wird.
Bei "SET NULL" nicht hilfreich, da nicht bekannt welcher Cocktail gelöscht wurde.

**Comment by phildhk** [comment]
ist erstmal ein datenbank thema, danach könnt ihr die log seite als neues issue an mich senden LOL aber vorher müsst ihr die db anpassen, das nicht mein bier

**Comment by FLXez** [comment]
@Schnietzel, @phildhk: Fehlt da noch was in der Tabelle?

**Comment by phildhk** [comment]
timestamp du pussystamp
