### ISSUE TITLE
Meldefunktion

### ISSUE THREAD

**Issue by FLXez** [FLXez/dbprog#48]
Neue Tabelle "Meldung"
- id
- melder_id
- meldung_art, ENUM(etab, etab_bew, cock, cock_bew, etab_cock, user)
- status, 0=offen 1=geschlossen
- etab_id, NULL
- cock_id, NULL
- user_id, NULL
- ts
Tabelle existiert.

Mods Profil:
- Meldungsübersicht
- kann Meldungen löschen (offen & geschlossene)

Admins Profil:
- Meldungsübersicht, nach Mod sortiert
- kann Meldungen "schließen"

**Comment by FLXez** [comment]
#13 sonst geht das nicht...

**Comment by FLXez** [comment]
@Schnietzel, @phildhk: Fehlt da noch was in der Tabelle?

**Comment by phildhk** [comment]
habs abgesegnet
